### ISSUE TITLE
Cannot access the network

### ISSUE THREAD

**Issue by zcadqewxs** [antmicro/kvm-aosp-jetson-nano#2]
I compiled it according to the tutorial，But unable to access the network
qemu keeps prompting this repeatedly

[  500.372532] init: Received control message 'interface_start' for 'android.hardware.radio@1.0::IRadio/slot1' from pid: 118 (/system/bin/hwservicemanager)
[  500.373149] init: Could not find 'android.hardware.radio@1.0::IRadio/slot1' for ctl.interface_start

--------------------
I try to ping，But not working
ping: unknown host google.com

--------------------
Battery information is incorrect
![image](https://user-images.githubusercontent.com/17941731/94650694-c941b080-0329-11eb-974a-904256f56ce2.png)

--------------------
![image](https://user-images.githubusercontent.com/17941731/94650757-e5455200-0329-11eb-97db-af0c871983ac.png)

Can you provide support?

**Comment by pgielda** [comment]
We do not support wifi in this release. We might add some connectivity in the future release.
Do you even have a battery? To have battery working you would have to integrate some kind of a battery gauge chip, integrate it with AOSP etc. 
In general Android Open Source Project is something you *customize*, not just run and hope to get all the features already there -- its not a desktop system but a system that has to be customized for the product you're building... So its missing a lot of features by default.
