### ISSUE TITLE
vanilla Jetson Nano compatibility

### ISSUE THREAD

**Issue by eadmaster** [antmicro/kvm-aosp-jetson-nano#3]
is this compatible with vanilla Jetson Nano boards too?

**Comment by pgielda** [comment]
Well Jetson Nano itself is a SoM. The whole thing runs on this SoM, so yes, in this sense its compatible with anything that has Jetson Nano in it and has a screen... Its a matter of customizing your kernel / devicetree etc for the correct baseboard. 
Internally its only tested by us with Open Source https://github.com/antmicro/jetson-nano-baseboard as this is the board we are interested in.
Feel free to test it on anything else of course.

**Comment by RaviBeagle** [comment]
Can the AOSP image run on QEMU-KVM on jetson nano ? Is there any customization I need to do ?

**Comment by pgielda** [comment]
We never tested but in principle its the same module, different motherboard so it should be doable. The goal here is to support the board I mentioned though.
