### ISSUE TITLE
build instruction for android 11

### ISSUE THREAD

**Issue by jerrygzy** [antmicro/kvm-aosp-jetson-nano#5]
I found this ROM build for rpi4, https://github.com/omnirom/android_device_brcm_rpi4  from omnirom.org

can we have a similar build on jetson nano?

**Comment by pgielda** [comment]
The instructions are targeting more or less a vanilla AOSP (Android Open Source Project) 10. 
We might update it to Android 11 some day, but nothing we plan to do near-term.
