### ISSUE TITLE
AOSP Sources quite large

### ISSUE THREAD

**Issue by RaviBeagle** [antmicro/kvm-aosp-jetson-nano#7]
Hello,

This is not an issue with the instructions as such.

I am trying ot build the AOSP and run it on in QEMU+KVM on my jetson nano.
However I dont have a separate system for build. The AOSP sources are quite large and download is taking a lot of time.

Could you suggest how to reduce the source sizes. Would these tips work ?

https://stackoverflow.com/questions/26761114/reduce-the-size-of-the-android-source-repository-repo-directory

Thanks

**Comment by RaviBeagle** [comment]
Please let me know. I have spent many hours downloading with a weak Windows laptop with Kubunut VM. 
There were some errors at the end. I try to do repo sync once again to see if everything is fine, but now its seems like its downloading all once again! 
(When I try to do repo sync with Jetson Nano the external HDD freezes because maybe it draws too much current)

**Comment by pgielda** [comment]
AOSP requires lots of resources to build. You typically cross-compile it on a huge machine with 100+ GB of free space and lots of GBs of RAM. I would probably not try it even on a laptop. Or at least expect problems.
In any case since its more a fixable issue I am closing this.
